#include "gmcore/SVGExporter.h"
#include <sstream>
#include <algorithm>
#include <cstdio>

namespace gmcore {

namespace {

std::string colorHex(const Color& c) {
    auto to255 = [](double v) {
        int i = (int)std::lround(std::max(0.0, std::min(1.0, v)) * 255.0);
        return i;
    };
    char buf[8];
    std::snprintf(buf, sizeof(buf), "#%02x%02x%02x", to255(c.r), to255(c.g), to255(c.b));
    return std::string(buf);
}

std::string fmt(double v) {
    char buf[32];
    std::snprintf(buf, sizeof(buf), "%.3f", v);
    return std::string(buf);
}

// One side of a patch: cubic Bezier from p0 to p1 with forward tangents t0,t1
// (t0/t1 already point in the direction of travel along this side).
struct Side { Vec2 p0, p1, t0, t1; };

std::string sidePathData(const Side& s) {
    Vec2 c1 = s.p0 + s.t0 * (1.0 / 3.0);
    Vec2 c2 = s.p1 - s.t1 * (1.0 / 3.0);
    std::ostringstream os;
    os << "C " << fmt(c1.x) << "," << fmt(c1.y) << " " << fmt(c2.x) << "," << fmt(c2.y)
       << " " << fmt(s.p1.x) << "," << fmt(s.p1.y);
    return os.str();
}

} // namespace

std::string exportGradientMeshSVG(const GradientMesh& mesh, int canvasWidth, int canvasHeight) {
    std::ostringstream svg;
    svg << "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n";
    svg << "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"" << canvasWidth << "\" height=\""
        << canvasHeight << "\" viewBox=\"0 0 " << canvasWidth << " " << canvasHeight << "\">\n";
    svg << "  <!-- Generated by GradientMeshStudio (gmcore).\n"
           "       Each mesh patch (Sun et al. 2007) is exported as its own single-patch\n"
           "       SVG2 <meshgradient>, painted behind a bounding <rect>; a mesh gradient\n"
           "       only paints inside its own patch boundary, so adjacent patches tile\n"
           "       seamlessly even though each is a separate <meshgradient> element.\n"
           "       This sidesteps SVG2's inter-patch implicit-shared-edge stop omission\n"
           "       rules, which are easy to get subtly wrong and unverifiable offline;\n"
           "       geometrically the boundary curves still match exactly, since both\n"
           "       patches are derived from the same shared control-point tangents.\n"
           "       Reading used for a patch's 4 <stop> elements: the Nth stop's\n"
           "       stop-color is the color at the START of that stop's own path\n"
           "       segment (i.e. the corner reached by the previous stop, or the\n"
           "       patch's local origin for the first stop). -->\n";
    svg << "  <defs>\n";

    int patchId = 0;
    std::vector<std::string> rects;
    for (int r = 0; r < mesh.rows - 1; ++r) {
        for (int c = 0; c < mesh.cols - 1; ++c, ++patchId) {
            HermiteCorner<Vec2> g00 = mesh.geomCorner(r, c);
            HermiteCorner<Vec2> g10 = mesh.geomCorner(r, c + 1);
            HermiteCorner<Vec2> g01 = mesh.geomCorner(r + 1, c);
            HermiteCorner<Vec2> g11 = mesh.geomCorner(r + 1, c + 1);
            Color col00 = mesh.at(r, c).C, col10 = mesh.at(r, c + 1).C;
            Color col11 = mesh.at(r + 1, c + 1).C, col01 = mesh.at(r + 1, c).C;

            Side top{g00.P, g10.P, g00.Pu, g10.Pu};
            Side right{g10.P, g11.P, g10.Pv, g11.Pv};
            Side bottom{g11.P, g01.P, g11.Pu * -1.0, g01.Pu * -1.0};
            Side left{g01.P, g00.P, g01.Pv * -1.0, g00.Pv * -1.0};

            double minX = std::min({g00.P.x, g10.P.x, g01.P.x, g11.P.x});
            double maxX = std::max({g00.P.x, g10.P.x, g01.P.x, g11.P.x});
            double minY = std::min({g00.P.y, g10.P.y, g01.P.y, g11.P.y});
            double maxY = std::max({g00.P.y, g10.P.y, g01.P.y, g11.P.y});

            std::string id = "p" + std::to_string(patchId);
            svg << "    <meshgradient id=\"" << id << "\" x=\"" << fmt(g00.P.x) << "\" y=\"" << fmt(g00.P.y)
                << "\" gradientUnits=\"userSpaceOnUse\">\n";
            svg << "      <meshrow>\n";
            svg << "        <meshpatch>\n";
            svg << "          <stop path=\"" << sidePathData(top) << "\" stop-color=\"" << colorHex(col00) << "\"/>\n";
            svg << "          <stop path=\"" << sidePathData(right) << "\" stop-color=\"" << colorHex(col10) << "\"/>\n";
            svg << "          <stop path=\"" << sidePathData(bottom) << "\" stop-color=\"" << colorHex(col11) << "\"/>\n";
            svg << "          <stop path=\"" << sidePathData(left) << "\" stop-color=\"" << colorHex(col01) << "\"/>\n";
            svg << "        </meshpatch>\n";
            svg << "      </meshrow>\n";
            svg << "    </meshgradient>\n";

            std::ostringstream rect;
            rect << "  <rect x=\"" << fmt(minX) << "\" y=\"" << fmt(minY) << "\" width=\"" << fmt(std::max(0.001, maxX - minX))
                 << "\" height=\"" << fmt(std::max(0.001, maxY - minY)) << "\" fill=\"url(#" << id << ")\"/>\n";
            rects.push_back(rect.str());
        }
    }
    svg << "  </defs>\n";
    for (const auto& r : rects) svg << r;
    svg << "</svg>\n";
    return svg.str();
}

} // namespace gmcore
